### PR TITLE
Freetype 2.8.1 upgrade

### PR DESCRIPTION
**Pull request by arun-govindan**

### CODE REVIEW

**Comment by dwrobel** [comment]
Works fine for me using native FT2.8 and fixes all off-by-one issues observed earlier (https://travis-ci.org/dwrobel/pxCore/builds/394530057#L7021).

**Comment by arun-govindan** [comment]
Hi Damian,
The externals caching has been merged to the master with freetype version 2.5.2.  So the freetype library present in the cache will be 2.5.2. But your branch has been merged with latest freetype. So your build is expecting a latest freetype version , which is not present in the stored cache.
So for running other PRs it is required to revert back the freetype2.8.1 or the external caching PR until it gets merged to the master.

**Comment by dwrobel** [comment]
> So for running other PRs it is required to revert back the freetype2.8.1 or the external caching PR until it gets merged to the master.

That doesn't sound good that it depends on changes on the master branch as it breaks the basic rule that the code should be buildable/usable on forks as well.

If I correctly understood you - anyone on their fork won't be able to upgrade any library because it will cause the issue like I'm observing now.

Can't simple the code be recompiled from the scratch if the cached version is not available somewhere?

**Comment by arun-govindan** [comment]
Hi Damian,

```If I correctly understood you - anyone on their fork won't be able to upgrade any library because it will cause the issue like I'm observing now.```
Using of different libraries in your repo is possible, but for that you need to delete the already stored cache.
The problem which i see in your scenario is that your master branch has freetype-2.5.2 cache and your onemw-wayland-egl-47 is running with freetype-2.8.1.
As the appveyor cache is shared by all the branches and as well as PRs from other accounts, it is required to maintain same library across all the branches or to delete the previous stored cache.
Deleting the cache can be done, by running the attached file with your account name.
[delete_appveyor_cache.zip](https://github.com/pxscene/pxCore/files/2133964/delete_appveyor_cache.zip)

```Can't simple the code be recompiled from the scratch if the cached version is not available somewhere?```
Currently the build will occur from scratch, only when there are changes in the folders zlib-1.2.11, WinSparkle pthread-2.9, libpng-1.6.28, libjpeg-turbo-1.5.1, glew-2.0.0, freetype-2.5.2, curl-7.40.0, jpeg-9a".

**Comment by dwrobel** [comment]
Even if I tried to use your latest version of this PR it still fails to build: https://ci.appveyor.com/project/dwrobel/pxcore/build/0dev.570#L20934

**Comment by arun-govindan** [comment]
The last change is not for solving this issue. I am currently working on a fix. Will update the PR once it is done.

**Comment by arun-govindan** [comment]
Hi @dwrobel , Can you please try with latest updates.

**Comment by dwrobel** [comment]
The latest version compiles fine although I don't see anything from the cache being used on consecutive builds. Please compare: 

- https://ci.appveyor.com/project/dwrobel/pxcore/build/0dev.578
- https://ci.appveyor.com/project/dwrobel/pxcore/build/0dev.581
- https://ci.appveyor.com/project/dwrobel/pxcore/build/0dev.582

**Comment by arun-govindan** [comment]
Hi Damian

For the builds 0dev.578 and 0dev.582, there are file changes in the external freetype directory, in that case the cache will not be used and the externals will be built completely to generate and store new cache.
And for the build 0dev.581, externals have not been built. It is using the stored cache. Please find the below logs from the build. The build starts from breakpad_client.sln and not with external.sln

*252Build started 7/13/2018 4:48:28 AM.
253     1>Project "C:\dw\pxCore\examples\pxScene2d\external\breakpad-chrome_55\src\client\windows\breakpad_client.sln" on node 1 (default targets).*

**Comment by dwrobel** [comment]
It's interesting as I merged the change in https://ci.appveyor.com/project/dwrobel/pxcore/build/0dev.577 and since then there were no changes to freetype (nor any other externals).

I now scheduled https://ci.appveyor.com/project/dwrobel/pxcore/build/0dev.583 simply by using `RE-BUILD COMMIT` button on `582` - let's see what would be the result.

**Comment by arun-govindan** [comment]
Builds 0dev.583, 0dev.582, 0dev.578, 0dev.577 are building the commit *77ac0709* which has the changes in the external type.
And because of that reason the caches is not being used.
Where as in build *0dev.581* the commit is *81ea8697* where there is no files changed in externals, so cache is being used.
I believe it works as expected, Please let me know if you have a different opinion

**Comment by dwrobel** [comment]
>Builds 0dev.583, 0dev.582,

It's not quite clear to me. My understanding is as following:
- 0dev.582 finished so the cache should be updated (whatever changed, if anything),
- 0dev.583 should re-use the cache from 0dev.582 - but it's not the case, could you please explain it?

**Comment by arun-govindan** [comment]
The decision on, whether to build the externals are not is done by validating the list of files that are present in the commit id which belongs to that build.
If there are file changes in the external directory, then external.sln will be called to create a new cache. If not, the external.sln will not be called, so the build will use the restored cache.

**Comment by dwrobel** [comment]
https://ci.appveyor.com/project/dwrobel/pxcore/build/0dev.587?fullLog=true#L244 seems to use the cache but looking at the compilation time there seems to be a tiny small gain.

BTW, have you look at https://github.com/frerich/clcache?

**Comment by arun-govindan** [comment]
Hi Damian,

The time saved for each build, when it uses the stored cache will be approximately between 6 to 10 minutes.  As the full build usually takes 44 to 50 minutes, the build that uses the caches can get completed in 35 to 40  minutes. However there can be few builds which might take a littler more time.

And regarding the clcache, I was not aware of it. I will look in to it.

Thanks.

**Comment by dwrobel** [comment]
I'm not sure what has changed in `testRunner` yesterday _(~ `10PM CEST`)_ but since https://semaphoreci.com/dwrobel/pxcore/branches/onemw-wayland-egl-49/builds/228 the `textbox auto.test0` test is failing as following all the time:

```textbox auto.test0:  FAILURE: measurements bounds.x2 should be 389 but is 367```

**Comment by arun-govindan** [comment]
Hi Damian,

Is this issue related to this PR or anyway related to me ?

**Comment by dwrobel** [comment]
I'm very happy with this PR as it fixes all the problems I was observing on `text measurements` so I'm just asking if the new regression which seems to be related also to `text` and `measurements` is somehow related to this PR or it's just the issue in one of the test from `testRunner`.

**Comment by dwrobel** [comment]
Arun, as per https://rdkm.slack.com/archives/C7RCDGLQ7/p1531922033000061 this seems to be related this PR as yesterday textbox_auto_v2.js was modified and this PR already uses this file:

```
-      {"url":"../tests/textbox_auto.js", "title":"textbox auto","useBaseURI":"true"},
+      {"url":"../tests/textbox_auto_v2.js", "title":"textbox auto","useBaseURI":"true"},
       {"url":"../tests/text2tests_v2.js", "title":"text2tests","useBaseURI":"true"},
       {"url":"../tests/test_xre2-85.js", "title":"test_XRE2-85","useBaseURI":"true"},
-      {"url":"../tests/test_y_coords.js", "title":"test_y_coords","useBaseURI":"true"},
+      {"url":"../tests/test_y_coords_v2.js", "title":"test_y_coords","useBaseURI":"true"},
```

**Pull request merged**
