### PR TITLE
Cached external libs, for reducing the appveyor build time.

### PR DESCRIPTION
**Pull request by arun-govindan**

### CODE REVIEW

**Comment by arun-govindan** [comment]
Hi Damian, Is it possible to give the link of this build, to verify further?
Because I tried these changes in a new branch and in appveyor the git diff-tree command works fine. so if I get the build link, I can check more on that.

**Comment by dwrobel** [comment]
>Hi Damian, Is it possible to give the link of this build, to verify further?

I simply did a local build on my PC.

Please note that as per: https://github.com/pxscene/pxCore/blob/master/ci/build_win32.bat#L3 build_win32.bat script is designed to:

>Script to build spark (aka pxscene) on
>Windows platform (locally and on AppVeyor)

Thus, it would be appreciated if it will keep working fine **locally** - which simplifies significantly the number of steps to build pxScene on Windows platform.

**Comment by arun-govindan** [comment]
Yeah Sure Damian, I will check for the alternatives to get the list of files and update the PR.

**Comment by arun-govindan** [comment]
Modified in such a way to build external for local build as it cannot have any cache to use.

**Pull request merged**
