### PR TITLE
framework caching updates

### PR DESCRIPTION
**Pull request by madanagopaltcomcast**

### CODE REVIEW

**Comment by npoltorapavlo** [comment]
@madanagopaltcomcast , your initial code uses caching like this: ‘src/lightning-web.js’ -> [many] versions. This PR does: URL -> [many] versions, which makes no sense because files from different URLs of the same version won't be shared. Caching from different URLs was the point of frameworks. My suggestion was to make **frameWorkCache** similar to **modmap**: URL -> [one] version, and copy the 2 blocks from _getModule_ marked as _If the module has been loaded already, return it._ and _Same file from different domains is shared if has 'version'._

**Comment by madanagopaltcomcast** [comment]
Thanks Nikita. is it like you meant, same framework code may be present in two servers http://server1/<code> and  http://server2/<code> with same hash?

**Comment by madanagopaltcomcast** [comment]
Scenario of multiple servers will be handled in current code, with same framework deployed in two different servers with same name property.

**Comment by npoltorapavlo** [comment]
Please do not merge this.
It breaks the current caching , and doesn't fix issues pointed out in ticket.

**Pull request merged**
