### PR TITLE
add exit test to testRunner

### PR DESCRIPTION
**Pull request by dwrobel**

### CODE REVIEW

**Comment by dwrobel** [comment]
This is just a proposal. The preferred solution would be to move the `exitTest.js` to the place other tests are located.

**Comment by conniefry** [comment]
@dwrobel The test is now published as https://px-apps.sys.comcast.net/pxscene-samples/examples/px-reference/tests/test_exit.js, so you should be able to use a relative path in the tests.json file.

**Comment by dwrobel** [comment]
> so you should be able to use a relative path in the tests.json file.

Thank you, PR has been updated accordingly.

**Comment by dwrobel** [comment]
Conflict resolved.

**Comment by dwrobel** [comment]
Switch to use v7 which should solve a build failure mentioned https://github.com/pxscene/pxCore/pull/1180#issuecomment-399062786.

**Pull request merged**
